// THIS FILE IS AUTO GENERATED, DO NOT MODIFY MANUALLY.

export type Language = "en" | "ar" | "fr" | "af";

export type DefaultLanguage = "en";

export type TranslationKey = "enabled_but_not" | "disabled" | "confirm" | "delete" | "remove" | "save" | "edit" | "year" | "month" | "day" | "or" | "download" | "person" | "datetime" | "save_changes" | "total_users" | "signed_in_users" | "dashboard_users_section_title" | "create_user" | "create_user_title" | "create_user_note" | "sites_access" | "full_sites_access" | "limited_sites_access" | "email" | "password" | "username" | "first_name" | "last_name" | "create_user_submit" | "search_users_placeholder" | "table_view" | "card_view" | "table_user" | "role" | "created_at" | "status" | "latitude" | "longitude" | "user_actions_profile" | "user_actions_edit" | "user_actions_copy_id" | "user_actions_copy_id_successful" | "user_actions_edit_form_note" | "user_actions_edit_success" | "user_actions_edit_error" | "user_actions_delete" | "user_actions_self_delete" | "user_actions_delete_confirm" | "user_actions_self_delete_confirm" | "user_actions_super_delete_error" | "user_actions_delete_success" | "user_actions_delete_error" | "dashboard_users_section_empty" | "change_password" | "language" | "theme" | "dashboard_settings_section_alerts_title" | "dashboard_settings_section_alerts_email" | "dashboard_settings_section_alerts_email_report" | "dashboard_settings_section_alerts_sound" | "dashboard_settings_section_alerts_popup" | "change_password_note" | "previous_password" | "new_password" | "confirm_password" | "change_password_submit" | "reset_settings" | "reset_settings_confirm" | "reset_settings_success" | "error_field_required" | "all_fields_required" | "error_internal_server" | "reset_settings_error" | "users_search_filter" | "upload_options" | "use_webcam" | "webcam_capture" | "upload_file" | "webcam_error" | "password_mismatch" | "password_minimum_length" | "no_access_re_login" | "user_delete_error" | "site_created" | "site_name" | "site_description" | "site_location_name" | "site_coordinates" | "site_priority_level" | "site_priority_level_input" | "priority_level_range_error" | "add_site" | "unknown" | "create_site_submit" | "create_site_title" | "sites_management" | "create_site_note" | "no_sites_found" | "sites_fetch_error" | "site_deleted" | "site_delete_error" | "site_action_delete" | "site_actions_delete_confirm" | "views" | "site_cameras" | "empty_cameras" | "map_loading" | "location_on_map" | "pick_location" | "map_pick_tools_title" | "zoom_level" | "sites_map_title" | "add_camera" | "new_camera_title" | "submit_camera" | "create_camera_note" | "camera_name" | "camera_stream_url" | "alerts_page_title" | "unsolved_issues" | "solved_issues" | "unsolved_issues_empty" | "solved_issues_empty_non_solved" | "solved_issues_empty_non_solved_note" | "solved_issues_empty_no_issue" | "alerts_fetch_error" | "site_settings_preference" | "cameras_setup" | "user_access_settings" | "camera_action_delete" | "camera_actions_delete_confirm" | "camera_deleted" | "camera_delete_error" | "add_user_access" | "edit_user_access_title" | "submit_user_access" | "edit_user_access_note" | "user_access_action_remove" | "user_access_action_remove_confirm" | "camera_settings" | "camera_events_settings" | "camera_details_settings" | "empty_user_access" | "assigned_users" | "installed_cameras" | "view_cameras" | "site_details" | "enable_alerts" | "on_motion_detection" | "on_motion_detection_note" | "on_person_detection" | "on_person_detection_note" | "on_fire_detection" | "on_fire_detection_note" | "on_ppe_detection" | "on_ppe_detection_note" | "on_licence_plate_detection" | "on_licence_plate_detection_note" | "on_car_detection" | "on_car_detection_note" | "record_duration_before_event" | "record_duration_before_event_note" | "record_duration_after_event" | "record_duration_after_event_note" | "solve_alert" | "unsolve_alert" | "share_alert" | "copy_alert_id" | "views_management" | "no_view_found" | "add_view" | "select_view" | "view_action_delete" | "view_actions_delete_confirm" | "stream_thumbnail_load_error" | "create_view_title" | "create_view_note" | "view_name" | "create_view" | "views_layout_editor" | "use_desktop_edit_view_layout" | "search_views" | "edit_view" | "delete_view" | "settings" | "display_language_lolll" | "display_language_note" | "app_theme" | "app_theme_note" | "dark_theme" | "light_theme" | "system_theme" | "preferences" | "appearance" | "accessibility" | "notifications" | "notification_sound" | "notification_sound_note" | "not_01" | "not_02" | "not_03" | "not_04" | "not_05" | "not_06" | "not_07" | "not_08" | "not_09" | "alert_notification_duration" | "alert_notification_duration_note" | "events" | "zones" | "event_affected_polygons" | "event_affected_polygons_note" | "stream_error" | "stream_error_refresh" | "retry" | "sidebar_tab_sites" | "sidebar_tab_alerts" | "sidebar_tab_views" | "sidebar_tab_map" | "sidebar_tab_users" | "sidebar_tab_settings" | "sidebar_tab_logout" | "sidebar_tab_logout_loading" | "en4" | "1fr" | "ar33" | "cancel333";

export type Translations = Record<TranslationKey, Record<Language, string>>;

export type TranslationVariables = {
  "enabled_but_not": [];
  "disabled": [];
  "confirm": [];
  "delete": [];
  "remove": [];
  "save": [];
  "edit": [];
  "year": [];
  "month": [];
  "day": [];
  "or": [];
  "download": [];
  "person": [];
  "datetime": [];
  "save_changes": [];
  "total_users": [];
  "signed_in_users": [];
  "dashboard_users_section_title": [];
  "create_user": [];
  "create_user_title": [];
  "create_user_note": [];
  "sites_access": [];
  "full_sites_access": [];
  "limited_sites_access": [];
  "email": [];
  "password": [];
  "username": [];
  "first_name": [];
  "last_name": [];
  "create_user_submit": [];
  "search_users_placeholder": [];
  "table_view": [];
  "card_view": [];
  "table_user": [];
  "role": [];
  "created_at": [];
  "status": [];
  "latitude": [];
  "longitude": [];
  "user_actions_profile": [];
  "user_actions_edit": [];
  "user_actions_copy_id": [];
  "user_actions_copy_id_successful": [];
  "user_actions_edit_form_note": [];
  "user_actions_edit_success": [];
  "user_actions_edit_error": [];
  "user_actions_delete": [];
  "user_actions_self_delete": [];
  "user_actions_delete_confirm": [
    userName: string | number
  ];
  "user_actions_self_delete_confirm": [
    userName: string | number
  ];
  "user_actions_super_delete_error": [];
  "user_actions_delete_success": [];
  "user_actions_delete_error": [];
  "dashboard_users_section_empty": [];
  "change_password": [];
  "language": [];
  "theme": [];
  "dashboard_settings_section_alerts_title": [];
  "dashboard_settings_section_alerts_email": [];
  "dashboard_settings_section_alerts_email_report": [];
  "dashboard_settings_section_alerts_sound": [];
  "dashboard_settings_section_alerts_popup": [];
  "change_password_note": [];
  "previous_password": [];
  "new_password": [];
  "confirm_password": [];
  "change_password_submit": [];
  "reset_settings": [];
  "reset_settings_confirm": [];
  "reset_settings_success": [];
  "error_field_required": [];
  "all_fields_required": [];
  "error_internal_server": [];
  "reset_settings_error": [];
  "users_search_filter": [];
  "upload_options": [];
  "use_webcam": [];
  "webcam_capture": [];
  "upload_file": [];
  "webcam_error": [];
  "password_mismatch": [];
  "password_minimum_length": [];
  "no_access_re_login": [];
  "user_delete_error": [];
  "site_created": [];
  "site_name": [];
  "site_description": [];
  "site_location_name": [];
  "site_coordinates": [];
  "site_priority_level": [];
  "site_priority_level_input": [];
  "priority_level_range_error": [];
  "add_site": [];
  "unknown": [];
  "create_site_submit": [];
  "create_site_title": [];
  "sites_management": [];
  "create_site_note": [];
  "no_sites_found": [];
  "sites_fetch_error": [];
  "site_deleted": [];
  "site_delete_error": [];
  "site_action_delete": [];
  "site_actions_delete_confirm": [];
  "views": [];
  "site_cameras": [];
  "empty_cameras": [];
  "map_loading": [];
  "location_on_map": [];
  "pick_location": [];
  "map_pick_tools_title": [];
  "zoom_level": [];
  "sites_map_title": [];
  "add_camera": [];
  "new_camera_title": [];
  "submit_camera": [];
  "create_camera_note": [];
  "camera_name": [];
  "camera_stream_url": [];
  "alerts_page_title": [];
  "unsolved_issues": [];
  "solved_issues": [];
  "unsolved_issues_empty": [];
  "solved_issues_empty_non_solved": [];
  "solved_issues_empty_non_solved_note": [];
  "solved_issues_empty_no_issue": [];
  "alerts_fetch_error": [];
  "site_settings_preference": [];
  "cameras_setup": [];
  "user_access_settings": [];
  "camera_action_delete": [];
  "camera_actions_delete_confirm": [
    cameraId: string | number
  ];
  "camera_deleted": [];
  "camera_delete_error": [];
  "add_user_access": [];
  "edit_user_access_title": [];
  "submit_user_access": [];
  "edit_user_access_note": [];
  "user_access_action_remove": [];
  "user_access_action_remove_confirm": [
    userName: string | number
  ];
  "camera_settings": [];
  "camera_events_settings": [];
  "camera_details_settings": [];
  "empty_user_access": [];
  "assigned_users": [];
  "installed_cameras": [];
  "view_cameras": [];
  "site_details": [];
  "enable_alerts": [];
  "on_motion_detection": [];
  "on_motion_detection_note": [];
  "on_person_detection": [];
  "on_person_detection_note": [];
  "on_fire_detection": [];
  "on_fire_detection_note": [];
  "on_ppe_detection": [];
  "on_ppe_detection_note": [];
  "on_licence_plate_detection": [];
  "on_licence_plate_detection_note": [];
  "on_car_detection": [];
  "on_car_detection_note": [];
  "record_duration_before_event": [];
  "record_duration_before_event_note": [];
  "record_duration_after_event": [];
  "record_duration_after_event_note": [];
  "solve_alert": [];
  "unsolve_alert": [];
  "share_alert": [];
  "copy_alert_id": [];
  "views_management": [];
  "no_view_found": [];
  "add_view": [];
  "select_view": [];
  "view_action_delete": [];
  "view_actions_delete_confirm": [
    viewId: string | number
  ];
  "stream_thumbnail_load_error": [];
  "create_view_title": [];
  "create_view_note": [];
  "view_name": [];
  "create_view": [];
  "views_layout_editor": [];
  "use_desktop_edit_view_layout": [];
  "search_views": [];
  "edit_view": [];
  "delete_view": [];
  "settings": [];
  "display_language_lolll": [];
  "display_language_note": [];
  "app_theme": [];
  "app_theme_note": [];
  "dark_theme": [];
  "light_theme": [];
  "system_theme": [];
  "preferences": [];
  "appearance": [];
  "accessibility": [];
  "notifications": [];
  "notification_sound": [];
  "notification_sound_note": [];
  "not_01": [];
  "not_02": [];
  "not_03": [];
  "not_04": [];
  "not_05": [];
  "not_06": [];
  "not_07": [];
  "not_08": [];
  "not_09": [];
  "alert_notification_duration": [];
  "alert_notification_duration_note": [];
  "events": [];
  "zones": [];
  "event_affected_polygons": [];
  "event_affected_polygons_note": [];
  "stream_error": [];
  "stream_error_refresh": [];
  "retry": [];
  "sidebar_tab_sites": [];
  "sidebar_tab_alerts": [];
  "sidebar_tab_views": [];
  "sidebar_tab_map": [];
  "sidebar_tab_users": [];
  "sidebar_tab_settings": [];
  "sidebar_tab_logout": [];
  "sidebar_tab_logout_loading": [];
  "en4": [];
  "1fr": [];
  "ar33": [];
  "cancel333": [];
};

export interface TranslationFileSchema {
  languages: Language[];
  defaultLanguage: Language;
  translations: Translations;
}