//* list taken from https://github.com/emvi/iso-639-1/blob/master/list.go

export default {
  af: { Code: "af", Name: "Afrikaans", NativeName: "Afrikaans" },
  am: { Code: "am", Name: "Amharic", NativeName: "አማርኛ" },
  ar: { Code: "ar", Name: "Arabic", NativeName: "اللغة العربية" },
  az: { Code: "az", Name: "Azerbaijani", NativeName: "Azərbaycan dili" },
  be: { Code: "be", Name: "Belarusian", NativeName: "Беларуская мова" },
  bg: { Code: "bg", Name: "Bulgarian", NativeName: "Български език" },
  bn: { Code: "bn", Name: "Bengali", NativeName: "বাংলা" },
  bs: { Code: "bs", Name: "Bosnian", NativeName: "Bosanski jezik" },
  ca: { Code: "ca", Name: "Catalan", NativeName: "Català" },
  cs: { Code: "cs", Name: "Czech", NativeName: "Čeština" },
  da: { Code: "da", Name: "Danish", NativeName: "Dansk" },
  de: { Code: "de", Name: "German", NativeName: "Deutsch" },
  el: { Code: "el", Name: "Greek", NativeName: "Ελληνικά" },
  en: { Code: "en", Name: "English", NativeName: "English" },
  es: { Code: "es", Name: "Spanish", NativeName: "Español" },
  et: { Code: "et", Name: "Estonian", NativeName: "Eesti" },
  fa: { Code: "fa", Name: "Persian", NativeName: "فارسی" },
  fi: { Code: "fi", Name: "Finnish", NativeName: "Suomi" },
  fr: { Code: "fr", Name: "French", NativeName: "Français" },
  ga: { Code: "ga", Name: "Irish", NativeName: "Gaeilge" },
  gl: { Code: "gl", Name: "Galician", NativeName: "Galego" },
  gu: { Code: "gu", Name: "Gujarati", NativeName: "ગુજરાતી" },
  he: { Code: "he", Name: "Hebrew", NativeName: "עברית" },
  hi: { Code: "hi", Name: "Hindi", NativeName: "हिन्दी" },
  hr: { Code: "hr", Name: "Croatian", NativeName: "Hrvatski jezik" },
  hu: { Code: "hu", Name: "Hungarian", NativeName: "Magyar" },
  id: { Code: "id", Name: "Indonesian", NativeName: "Indonesian" },
  is: { Code: "is", Name: "Icelandic", NativeName: "Íslenska" },
  it: { Code: "it", Name: "Italian", NativeName: "Italiano" },
  ja: { Code: "ja", Name: "Japanese", NativeName: "日本語" },
  jv: { Code: "jv", Name: "Javanese", NativeName: "Basa Jawa" },
  ka: { Code: "ka", Name: "Georgian", NativeName: "Ქართული" },
  kk: { Code: "kk", Name: "Kazakh", NativeName: "Қазақ тілі" },
  km: { Code: "km", Name: "Khmer", NativeName: "ខេមរភាសា" },
  kn: { Code: "kn", Name: "Kannada", NativeName: "ಕನ್ನಡ" },
  ko: { Code: "ko", Name: "Korean", NativeName: "한국어" },
  ky: { Code: "ky", Name: "Kyrgyz", NativeName: "Кыргыз тили" },
  lo: { Code: "lo", Name: "Lao", NativeName: "ພາສາລາວ" },
  lt: { Code: "lt", Name: "Lithuanian", NativeName: "Lietuvių" },
  lv: { Code: "lv", Name: "Latvian", NativeName: "Latviešu" },
  mk: { Code: "mk", Name: "Macedonian", NativeName: "Македонски јазик" },
  ml: { Code: "ml", Name: "Malayalam", NativeName: "മലയാളം" },
  mn: { Code: "mn", Name: "Mongolian", NativeName: "Монгол хэл" },
  mr: { Code: "mr", Name: "Marathi", NativeName: "मराठी" },
  ms: { Code: "ms", Name: "Malay", NativeName: "Bahasa Melayu" },
  mt: { Code: "mt", Name: "Maltese", NativeName: "Malti" },
  my: { Code: "my", Name: "Burmese", NativeName: "မြန်မာစာ" },
  ne: { Code: "ne", Name: "Nepali", NativeName: "नेपाली" },
  nl: { Code: "nl", Name: "Dutch", NativeName: "Nederlands" },
  no: { Code: "no", Name: "Norwegian", NativeName: "Norsk" },
  pa: { Code: "pa", Name: "Punjabi", NativeName: "ਪੰਜਾਬੀ" },
  pl: { Code: "pl", Name: "Polish", NativeName: "Polski" },
  ps: { Code: "ps", Name: "Pashto", NativeName: "پښتو" },
  pt: { Code: "pt", Name: "Portuguese", NativeName: "Português" },
  ro: { Code: "ro", Name: "Romanian", NativeName: "Română" },
  ru: { Code: "ru", Name: "Russian", NativeName: "Русский" },
  si: { Code: "si", Name: "Sinhala", NativeName: "සිංහල" },
  sk: { Code: "sk", Name: "Slovak", NativeName: "Slovenčina" },
  sl: { Code: "sl", Name: "Slovenian", NativeName: "Slovenščina" },
  sq: { Code: "sq", Name: "Albanian", NativeName: "Shqip" },
  sr: { Code: "sr", Name: "Serbian", NativeName: "Српски језик" },
  sv: { Code: "sv", Name: "Swedish", NativeName: "Svenska" },
  sw: { Code: "sw", Name: "Swahili", NativeName: "Kiswahili" },
  ta: { Code: "ta", Name: "Tamil", NativeName: "தமிழ்" },
  te: { Code: "te", Name: "Telugu", NativeName: "తెలుగు" },
  th: { Code: "th", Name: "Thai", NativeName: "ไทย" },
  tr: { Code: "tr", Name: "Turkish", NativeName: "Türkçe" },
  uk: { Code: "uk", Name: "Ukrainian", NativeName: "Українська" },
  ur: { Code: "ur", Name: "Urdu", NativeName: "اُردُو" },
  uz: { Code: "uz", Name: "Uzbek", NativeName: "Ўзбек" },
  vi: { Code: "vi", Name: "Vietnamese", NativeName: "Tiếng Việt" },
  zh: { Code: "zh", Name: "Chinese", NativeName: "中文" },
};
