openapi: 3.0.0
info:
  title: QTrans API
  description: API documentation for QTrans
  version: 1.0.0
paths:
  /api/translations:
    get:
      summary: Get all translations
      responses:
        200:
          description: A list of all translations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    translations:
                      type: object
                      properties:
                        en:
                          type: string
    post:
      summary: Create a new translation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                translation:
                  type: object
                  properties:
                    en:
                      type: string
      responses:
        201:
          description: Translation created
  /api/translations/{translationKey}:
    get:
      summary: Get a translation
      parameters:
        - in: path
          name: translationKey
          required: true
          schema:
            type: string
      responses:
        200:
          description: Translation found
        404:
          description: Translation not found
    patch:
      summary: Update an existing translation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                translation:
                  type: object
                  properties:
                    en:
                      type: string
      responses:
        200:
          description: Translation updated
    delete:
      summary: Delete a translation
      parameters:
        - in: path
          name: translationKey
          required: true
          schema:
            type: string
      responses:
        200:
          description: Translation deleted
        404:
          description: Translation not found
